# ============================================================
# Desktop Host Configuration
# Entry point: /etc/nixos/configuration.nix should import this,
# or symlink to it.
# ============================================================

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config
    ../../modules/base.nix         # shared settings (locale, fonts, etc.)
    ../../modules/apps.nix         # GUI & CLI applications
    ../../modules/shell.nix        # zsh, aliases, environment
    ../../modules/git.nix          # git + GitHub tooling
    ../../home/default.nix         # home-manager user config
    ../../modules/wireguard.nix
  ];

  # ── Machine identity ────────────────────────────────────────
  networking.hostName = "nixos-notebook";

  # ── Boot ────────────────────────────────────────────────────
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # ── Hardware ────────────────────────────────────────────────

  # --- AMD ---
  hardware.opengl.enable = true;
  hardware.opengl.driSupport = true;

  # ── Bluetooth ───────────────────────────────────────────────
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ── Sound (PipeWire) ────────────────────────────────────────
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User account ────────────────────────────────────────────
  users.users.yourname = { # TO_CHANGE
    isNormalUser = true;
    description = "Your Name"; # TO_CHANGE
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    shell = pkgs.zsh;
  };

  # ── This value pins the NixOS version for stateful options.
  # Do NOT change this after first install.
  system.stateVersion = "25.11";
}

