# ============================================================
# Desktop Host Configuration
# Entry point: /etc/nixos/configuration.nix should import this,
# or symlink to it.
# ============================================================

{ config, pkgs, ... }:

{
  imports = [
    ./hardware-configuration.nix   # generated by nixos-generate-config
    ../../modules/base.nix         # shared settings (locale, fonts, etc.)
    ../../modules/desktop-kde.nix  # KDE Plasma + display server
    ../../modules/apps.nix         # GUI & CLI applications
    ../../modules/shell.nix        # zsh, aliases, environment
    ../../modules/git.nix          # git + GitHub tooling
    ../../home/default.nix         # home-manager user config
  ];

  # ── Machine identity ────────────────────────────────────────
  networking.hostName = "nixos-desktop";

  # ── Boot ────────────────────────────────────────────────────
  boot.loader.grub.enable = true;
  boot.loader.grub.device = "/dev/sda";
  boot.loader.grub.useOSProber = true;

  # ── Hardware ────────────────────────────────────────────────
  # Adjust these to match your actual hardware.
  # Run `lspci | grep -i vga` to find your GPU vendor.

  # Uncomment ONE of the following GPU blocks:

  # --- NVIDIA ---
  # services.xserver.videoDrivers = [ "nvidia" ];
  # hardware.nvidia.modesetting.enable = true;
  # hardware.nvidia.open = false; # set true for open-source kernel module (Turing+)
  # hardware.opengl.enable = true;

  # --- AMD ---
  # hardware.opengl.enable = true;
  # hardware.opengl.driSupport = true;

  # --- Intel ---
  # hardware.opengl.enable = true;

  # ── CPU microcode ───────────────────────────────────────────
  # Uncomment the one matching your CPU:
  # hardware.cpu.amd.updateMicrocode = true;
  # hardware.cpu.intel.updateMicrocode = true;

  # ── Bluetooth ───────────────────────────────────────────────
  hardware.bluetooth.enable = true;
  services.blueman.enable = true;

  # ── Sound (PipeWire) ────────────────────────────────────────
  security.rtkit.enable = true;
  services.pipewire = {
    enable = true;
    alsa.enable = true;
    alsa.support32Bit = true;
    pulse.enable = true;
  };

  # ── User account ────────────────────────────────────────────
  users.users.yourname = { # TO_CHANGE
    isNormalUser = true;
    description = "Your Name"; # TO_CHANGE
    extraGroups = [ "wheel" "networkmanager" "audio" "video" ];
    shell = pkgs.zsh;
  };

  nixpkgs.config.permittedInsecurePackages = [
    "openssl-1.1.1w"
  ];


  # ── This value pins the NixOS version for stateful options.
  # Do NOT change this after first install.
  system.stateVersion = "25.11";
}
